apiVersion: apps/v1
kind: Deployment
metadata:
  name: kr8sserver-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kr8sserver
  template:
    metadata:
      labels:
        app: kr8sserver
    spec:
      containers:
        - name: kr8sserver
          image: kr8sserver/server
---
apiVersion: v1
kind: Service
metadata:
  name: kr8sserver-np-srv
spec: 
  type: NodePort
  selector:
    app: kr8sserver
  ports:
    - name: kr8sserver
      protocol: TCP
      port: 3500
      targetPort: 3400
      nodePort: 31000